name: Python CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools wheel
        pip install -r requirements.txt
    
    - name: Create package files
      run: |
        echo "[build-system]
        requires = ['setuptools>=42']
        build-backend = 'setuptools.build_meta'
        
        [project]
        name = 'bfs-community-graph'
        version = '${GITHUB_REF#refs/tags/v}'
        description = 'BFS Community Graph Analysis Tool'
        readme = 'README.md'
        requires-python = '>=3.8'
        dependencies = [
            'networkx',
            'matplotlib'
        ]" > pyproject.toml
    
    - name: Build package
      run: python -m build
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        body: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/*
